export default function Header({ title }: { title: string }) {
    if (!title) {
        title = `${title.concat('Sin titulo | T3-TODO-APP')}`
    } else {
        title = `${title.concat(' | T3-TODO-APP')}`
    }
    return (

        <>
            <title>{title}</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </>
    )
}